# Generated by Django 3.0.4 on 2020-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('good', models.IntegerField(blank=True, default=0, null=True)),
                ('goodmember', models.CharField(blank=True, default='a', max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('introduce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('introduce', models.TextField()),
            ],
        ),
    ]
