# Generated by Django 3.0.4 on 2020-03-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='author',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='url_code',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
