# Generated by Django 3.0.4 on 2020-03-31 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outputapp', '0002_auto_20200331_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='introduce',
        ),
    ]
