# Generated by Django 3.0.4 on 2020-04-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputapp', '0003_auto_20200331_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='url_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
