# Generated by Django 3.0.4 on 2020-04-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outputapp', '0004_auto_20200401_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_code', models.CharField(max_length=50, null=True, unique=True, verbose_name='URLコード')),
            ],
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='url_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outputapp.Category', verbose_name='カテゴリー'),
        ),
    ]
