# Generated by Django 3.0.4 on 2020-04-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outputapp', '0005_auto_20200401_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='url_code',
            new_name='category',
        ),
    ]
