# Generated by Django 3.0.4 on 2020-04-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputapp', '0007_auto_20200401_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='url_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
