# Generated by Django 3.0.4 on 2020-04-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputapp', '0010_boardmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='icon',
            field=models.ImageField(default='aaa', upload_to=''),
            preserve_default=False,
        ),
    ]
